# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1119, 578)
        MainWindow.setDocumentMode(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.MainTitle = QtWidgets.QLabel(self.centralWidget)
        self.MainTitle.setGeometry(QtCore.QRect(270, 20, 461, 41))
        self.MainTitle.setTextFormat(QtCore.Qt.RichText)
        self.MainTitle.setScaledContents(False)
        self.MainTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.MainTitle.setWordWrap(False)
        self.MainTitle.setObjectName("MainTitle")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(420, 100, 611, 391))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_train = QtWidgets.QWidget()
        self.tab_train.setObjectName("tab_train")
        self.comboBox_indexLevel = QtWidgets.QComboBox(self.tab_train)
        self.comboBox_indexLevel.setGeometry(QtCore.QRect(80, 30, 101, 21))
        self.comboBox_indexLevel.setObjectName("comboBox_indexLevel")
        self.comboBox_indexName = QtWidgets.QComboBox(self.tab_train)
        self.comboBox_indexName.setGeometry(QtCore.QRect(80, 80, 101, 21))
        self.comboBox_indexName.setObjectName("comboBox_indexName")
        self.label_indexLevel = QtWidgets.QLabel(self.tab_train)
        self.label_indexLevel.setGeometry(QtCore.QRect(10, 30, 61, 21))
        self.label_indexLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_indexLevel.setObjectName("label_indexLevel")
        self.label_indexName = QtWidgets.QLabel(self.tab_train)
        self.label_indexName.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.label_indexName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_indexName.setObjectName("label_indexName")
        self.pushButton_selectTrain = QtWidgets.QPushButton(self.tab_train)
        self.pushButton_selectTrain.setGeometry(QtCore.QRect(80, 210, 101, 31))
        self.pushButton_selectTrain.setObjectName("pushButton_selectTrain")
        self.command_startTrain = QtWidgets.QPushButton(self.tab_train)
        self.command_startTrain.setGeometry(QtCore.QRect(80, 260, 101, 31))
        self.command_startTrain.setObjectName("command_startTrain")
        self.groupBox = QtWidgets.QGroupBox(self.tab_train)
        self.groupBox.setGeometry(QtCore.QRect(270, 30, 261, 311))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 20, 71, 16))
        self.label.setObjectName("label")
        self.lineEdit_lr = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_lr.setGeometry(QtCore.QRect(110, 20, 51, 16))
        self.lineEdit_lr.setObjectName("lineEdit_lr")
        self.lineEdit_epoch = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_epoch.setGeometry(QtCore.QRect(110, 50, 51, 16))
        self.lineEdit_epoch.setObjectName("lineEdit_epoch")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 71, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 71, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_batch = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_batch.setGeometry(QtCore.QRect(110, 80, 51, 16))
        self.lineEdit_batch.setObjectName("lineEdit_batch")
        self.groupBox_nodeNum = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_nodeNum.setGeometry(QtCore.QRect(10, 130, 171, 141))
        self.groupBox_nodeNum.setObjectName("groupBox_nodeNum")
        self.checkBox_lv1 = QtWidgets.QCheckBox(self.groupBox_nodeNum)
        self.checkBox_lv1.setGeometry(QtCore.QRect(30, 50, 71, 16))
        self.checkBox_lv1.setObjectName("checkBox_lv1")
        self.lineEdit_lv1 = QtWidgets.QLineEdit(self.groupBox_nodeNum)
        self.lineEdit_lv1.setGeometry(QtCore.QRect(100, 50, 51, 16))
        self.lineEdit_lv1.setText("")
        self.lineEdit_lv1.setObjectName("lineEdit_lv1")
        self.checkBox_lv2 = QtWidgets.QCheckBox(self.groupBox_nodeNum)
        self.checkBox_lv2.setGeometry(QtCore.QRect(30, 80, 71, 16))
        self.checkBox_lv2.setObjectName("checkBox_lv2")
        self.lineEdit_lv2 = QtWidgets.QLineEdit(self.groupBox_nodeNum)
        self.lineEdit_lv2.setGeometry(QtCore.QRect(100, 80, 51, 16))
        self.lineEdit_lv2.setObjectName("lineEdit_lv2")
        self.checkBox_lv3 = QtWidgets.QCheckBox(self.groupBox_nodeNum)
        self.checkBox_lv3.setGeometry(QtCore.QRect(30, 110, 71, 16))
        self.checkBox_lv3.setObjectName("checkBox_lv3")
        self.lineEdit_lv3 = QtWidgets.QLineEdit(self.groupBox_nodeNum)
        self.lineEdit_lv3.setGeometry(QtCore.QRect(100, 110, 51, 16))
        self.lineEdit_lv3.setObjectName("lineEdit_lv3")
        self.tabWidget.addTab(self.tab_train, "")
        self.tab_test = QtWidgets.QWidget()
        self.tab_test.setObjectName("tab_test")
        self.pushButton_selectEvaluate = QtWidgets.QPushButton(self.tab_test)
        self.pushButton_selectEvaluate.setGeometry(QtCore.QRect(80, 70, 101, 31))
        self.pushButton_selectEvaluate.setObjectName("pushButton_selectEvaluate")
        self.command_startEvaluate = QtWidgets.QPushButton(self.tab_test)
        self.command_startEvaluate.setGeometry(QtCore.QRect(80, 120, 101, 31))
        self.command_startEvaluate.setObjectName("command_startEvaluate")
        self.label_testIndexName = QtWidgets.QLabel(self.tab_test)
        self.label_testIndexName.setGeometry(QtCore.QRect(10, 30, 61, 20))
        self.label_testIndexName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_testIndexName.setObjectName("label_testIndexName")
        self.comboBox_testIndex = QtWidgets.QComboBox(self.tab_test)
        self.comboBox_testIndex.setGeometry(QtCore.QRect(80, 30, 101, 21))
        self.comboBox_testIndex.setObjectName("comboBox_testIndex")
        self.push_retest = QtWidgets.QPushButton(self.tab_test)
        self.push_retest.setGeometry(QtCore.QRect(410, 280, 101, 31))
        self.push_retest.setMouseTracking(False)
        self.push_retest.setWhatsThis("")
        self.push_retest.setObjectName("push_retest")
        self.label_indexweight_2 = QtWidgets.QLabel(self.tab_test)
        self.label_indexweight_2.setGeometry(QtCore.QRect(340, 30, 61, 20))
        self.label_indexweight_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_indexweight_2.setObjectName("label_indexweight_2")
        self.lineEdit_result = QtWidgets.QLineEdit(self.tab_test)
        self.lineEdit_result.setGeometry(QtCore.QRect(410, 30, 101, 21))
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.group_evaluate = QtWidgets.QGroupBox(self.tab_test)
        self.group_evaluate.setGeometry(QtCore.QRect(340, 70, 211, 91))
        self.group_evaluate.setObjectName("group_evaluate")
        self.push_showresult = QtWidgets.QPushButton(self.group_evaluate)
        self.push_showresult.setGeometry(QtCore.QRect(70, 10, 101, 31))
        self.push_showresult.setObjectName("push_showresult")
        self.push_printresult = QtWidgets.QPushButton(self.group_evaluate)
        self.push_printresult.setGeometry(QtCore.QRect(70, 50, 101, 31))
        self.push_printresult.setObjectName("push_printresult")
        self.tabWidget.addTab(self.tab_test, "")
        self.group_index = QtWidgets.QGroupBox(self.centralWidget)
        self.group_index.setGeometry(QtCore.QRect(20, 100, 341, 391))
        self.group_index.setObjectName("group_index")
        self.tree_index = QtWidgets.QTreeWidget(self.group_index)
        self.tree_index.setGeometry(QtCore.QRect(20, 30, 291, 291))
        self.tree_index.setEditTriggers(
            QtWidgets.QAbstractItemView.AnyKeyPressed | QtWidgets.QAbstractItemView.DoubleClicked | QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tree_index.setRootIsDecorated(True)
        self.tree_index.setUniformRowHeights(True)
        self.tree_index.setHeaderHidden(False)
        self.tree_index.setObjectName("tree_index")
        self.tree_index.header().setVisible(True)
        self.tree_index.header().setCascadingSectionResizes(True)
        self.tree_index.header().setDefaultSectionSize(200)
        self.tree_index.header().setMinimumSectionSize(50)
        self.tree_index.header().setStretchLastSection(True)
        self.push_editIndex = QtWidgets.QPushButton(self.group_index)
        self.push_editIndex.setGeometry(QtCore.QRect(190, 340, 121, 31))
        self.push_editIndex.setObjectName("push_editIndex")
        self.push_selectIndex = QtWidgets.QPushButton(self.group_index)
        self.push_selectIndex.setGeometry(QtCore.QRect(20, 340, 121, 31))
        self.push_selectIndex.setObjectName("push_selectIndex")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1119, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setTitle("")
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于深度学习的雷达/侦察系统效能评估软件"))
        self.MainTitle.setText(_translate("MainWindow",
                                          "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">基于深度学习的雷达/侦察系统效能评估软件</span></p></body></html>"))
        self.label_indexLevel.setText(_translate("MainWindow", "指标层级"))
        self.label_indexName.setText(_translate("MainWindow", "指标名称"))
        self.pushButton_selectTrain.setText(_translate("MainWindow", "选择样本数据"))
        self.command_startTrain.setText(_translate("MainWindow", "开始训练"))
        self.groupBox.setTitle(_translate("MainWindow", "参数调节"))
        self.label.setText(_translate("MainWindow", "训练学习速率"))
        self.label_2.setText(_translate("MainWindow", "迭代次数"))
        self.label_3.setText(_translate("MainWindow", "Batch大小"))
        self.groupBox_nodeNum.setTitle(_translate("MainWindow", "节点数量"))
        self.checkBox_lv1.setText(_translate("MainWindow", "第一层"))
        self.checkBox_lv2.setText(_translate("MainWindow", "第二层"))
        self.checkBox_lv3.setText(_translate("MainWindow", "第三层"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_train), _translate("MainWindow", "训练"))
        self.pushButton_selectEvaluate.setText(_translate("MainWindow", "选择评估数据"))
        self.command_startEvaluate.setText(_translate("MainWindow", "开始评估"))
        self.label_testIndexName.setText(_translate("MainWindow", "指标名称"))
        self.push_retest.setText(_translate("MainWindow", "重新测试"))
        self.label_indexweight_2.setText(_translate("MainWindow", "评估结果"))
        self.group_evaluate.setTitle(_translate("MainWindow", "评估报告"))
        self.push_showresult.setText(_translate("MainWindow", "查看"))
        self.push_printresult.setText(_translate("MainWindow", "打印"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_test), _translate("MainWindow", "测试"))
        self.group_index.setTitle(_translate("MainWindow", "指标"))
        self.tree_index.headerItem().setText(0, _translate("MainWindow", "指标体系"))
        self.tree_index.headerItem().setText(1, _translate("MainWindow", "权重"))
        self.push_editIndex.setText(_translate("MainWindow", "保存"))
        self.push_selectIndex.setText(_translate("MainWindow", "选择指标文件"))
