# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1073, 533)
        MainWindow.setDocumentMode(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.MainTitle = QtWidgets.QLabel(self.centralWidget)
        self.MainTitle.setGeometry(QtCore.QRect(350, 20, 241, 41))
        self.MainTitle.setTextFormat(QtCore.Qt.RichText)
        self.MainTitle.setScaledContents(False)
        self.MainTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.MainTitle.setWordWrap(False)
        self.MainTitle.setObjectName("MainTitle")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(420, 100, 591, 351))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_train = QtWidgets.QWidget()
        self.tab_train.setObjectName("tab_train")
        self.comboBox_indexLevel = QtWidgets.QComboBox(self.tab_train)
        self.comboBox_indexLevel.setGeometry(QtCore.QRect(130, 30, 69, 22))
        self.comboBox_indexLevel.setObjectName("comboBox_indexLevel")
        self.comboBox_indexName = QtWidgets.QComboBox(self.tab_train)
        self.comboBox_indexName.setGeometry(QtCore.QRect(130, 80, 69, 22))
        self.comboBox_indexName.setObjectName("comboBox_indexName")
        self.label_indexLevel = QtWidgets.QLabel(self.tab_train)
        self.label_indexLevel.setGeometry(QtCore.QRect(60, 30, 61, 21))
        self.label_indexLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_indexLevel.setObjectName("label_indexLevel")
        self.label_indexName = QtWidgets.QLabel(self.tab_train)
        self.label_indexName.setGeometry(QtCore.QRect(60, 80, 61, 21))
        self.label_indexName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_indexName.setObjectName("label_indexName")
        self.groupBox_nodeNum = QtWidgets.QGroupBox(self.tab_train)
        self.groupBox_nodeNum.setGeometry(QtCore.QRect(50, 140, 181, 181))
        self.groupBox_nodeNum.setObjectName("groupBox_nodeNum")
        self.checkBox_lv1 = QtWidgets.QCheckBox(self.groupBox_nodeNum)
        self.checkBox_lv1.setGeometry(QtCore.QRect(30, 50, 71, 16))
        self.checkBox_lv1.setObjectName("checkBox_lv1")
        self.lineEdit_lv1 = QtWidgets.QLineEdit(self.groupBox_nodeNum)
        self.lineEdit_lv1.setGeometry(QtCore.QRect(100, 50, 41, 16))
        self.lineEdit_lv1.setText("")
        self.lineEdit_lv1.setObjectName("lineEdit_lv1")
        self.checkBox_lv2 = QtWidgets.QCheckBox(self.groupBox_nodeNum)
        self.checkBox_lv2.setGeometry(QtCore.QRect(30, 80, 71, 16))
        self.checkBox_lv2.setObjectName("checkBox_lv2")
        self.lineEdit_lv2 = QtWidgets.QLineEdit(self.groupBox_nodeNum)
        self.lineEdit_lv2.setGeometry(QtCore.QRect(100, 80, 41, 16))
        self.lineEdit_lv2.setObjectName("lineEdit_lv2")
        self.checkBox_lv3 = QtWidgets.QCheckBox(self.groupBox_nodeNum)
        self.checkBox_lv3.setGeometry(QtCore.QRect(30, 110, 71, 16))
        self.checkBox_lv3.setObjectName("checkBox_lv3")
        self.lineEdit_lv3 = QtWidgets.QLineEdit(self.groupBox_nodeNum)
        self.lineEdit_lv3.setGeometry(QtCore.QRect(100, 110, 41, 16))
        self.lineEdit_lv3.setObjectName("lineEdit_lv3")
        self.pushButton_selectTrain = QtWidgets.QPushButton(self.tab_train)
        self.pushButton_selectTrain.setGeometry(QtCore.QRect(320, 280, 121, 31))
        self.pushButton_selectTrain.setObjectName("pushButton_selectTrain")
        self.command_startTrain = QtWidgets.QPushButton(self.tab_train)
        self.command_startTrain.setGeometry(QtCore.QRect(450, 280, 121, 31))
        self.command_startTrain.setObjectName("command_startTrain")
        self.tabWidget.addTab(self.tab_train, "")
        self.tab_test = QtWidgets.QWidget()
        self.tab_test.setObjectName("tab_test")
        self.pushButton_selectEvaluate = QtWidgets.QPushButton(self.tab_test)
        self.pushButton_selectEvaluate.setGeometry(QtCore.QRect(320, 280, 121, 31))
        self.pushButton_selectEvaluate.setObjectName("pushButton_selectEvaluate")
        self.command_startEvaluate = QtWidgets.QPushButton(self.tab_test)
        self.command_startEvaluate.setGeometry(QtCore.QRect(450, 280, 121, 31))
        self.command_startEvaluate.setObjectName("command_startEvaluate")
        self.lineEdit_indexName = QtWidgets.QLineEdit(self.tab_test)
        self.lineEdit_indexName.setGeometry(QtCore.QRect(90, 70, 113, 20))
        self.lineEdit_indexName.setText("")
        self.lineEdit_indexName.setObjectName("lineEdit_indexName")
        self.label_testIndexName = QtWidgets.QLabel(self.tab_test)
        self.label_testIndexName.setGeometry(QtCore.QRect(20, 70, 61, 20))
        self.label_testIndexName.setAlignment(QtCore.Qt.AlignCenter)
        self.label_testIndexName.setObjectName("label_testIndexName")
        self.label_indexweight = QtWidgets.QLabel(self.tab_test)
        self.label_indexweight.setGeometry(QtCore.QRect(20, 120, 61, 20))
        self.label_indexweight.setAlignment(QtCore.Qt.AlignCenter)
        self.label_indexweight.setObjectName("label_indexweight")
        self.lineEdit_indexWeight = QtWidgets.QLineEdit(self.tab_test)
        self.lineEdit_indexWeight.setGeometry(QtCore.QRect(90, 120, 113, 20))
        self.lineEdit_indexWeight.setObjectName("lineEdit_indexWeight")
        self.tabWidget.addTab(self.tab_test, "")
        self.tab_evaluate = QtWidgets.QWidget()
        self.tab_evaluate.setObjectName("tab_evaluate")
        self.group_evaluate = QtWidgets.QGroupBox(self.tab_evaluate)
        self.group_evaluate.setGeometry(QtCore.QRect(270, 260, 301, 51))
        self.group_evaluate.setObjectName("group_evaluate")
        self.push_showresult = QtWidgets.QPushButton(self.group_evaluate)
        self.push_showresult.setGeometry(QtCore.QRect(80, 20, 75, 23))
        self.push_showresult.setObjectName("push_showresult")
        self.push_printresult = QtWidgets.QPushButton(self.group_evaluate)
        self.push_printresult.setGeometry(QtCore.QRect(170, 20, 75, 23))
        self.push_printresult.setObjectName("push_printresult")
        self.lineEdit_indexName_2 = QtWidgets.QLineEdit(self.tab_evaluate)
        self.lineEdit_indexName_2.setGeometry(QtCore.QRect(90, 70, 113, 20))
        self.lineEdit_indexName_2.setText("")
        self.lineEdit_indexName_2.setObjectName("lineEdit_indexName_2")
        self.lineEdit_result = QtWidgets.QLineEdit(self.tab_evaluate)
        self.lineEdit_result.setGeometry(QtCore.QRect(90, 120, 113, 20))
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.label_testIndexName_2 = QtWidgets.QLabel(self.tab_evaluate)
        self.label_testIndexName_2.setGeometry(QtCore.QRect(20, 70, 61, 20))
        self.label_testIndexName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_testIndexName_2.setObjectName("label_testIndexName_2")
        self.label_indexweight_2 = QtWidgets.QLabel(self.tab_evaluate)
        self.label_indexweight_2.setGeometry(QtCore.QRect(20, 120, 61, 20))
        self.label_indexweight_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_indexweight_2.setObjectName("label_indexweight_2")
        self.push_retest = QtWidgets.QPushButton(self.tab_evaluate)
        self.push_retest.setGeometry(QtCore.QRect(390, 90, 91, 31))
        self.push_retest.setObjectName("push_retest")
        self.tabWidget.addTab(self.tab_evaluate, "")
        self.group_index = QtWidgets.QGroupBox(self.centralWidget)
        self.group_index.setGeometry(QtCore.QRect(20, 100, 301, 351))
        self.group_index.setObjectName("group_index")
        self.tree_index = QtWidgets.QTreeWidget(self.group_index)
        self.tree_index.setGeometry(QtCore.QRect(20, 30, 261, 251))
        self.tree_index.setEditTriggers(
            QtWidgets.QAbstractItemView.AnyKeyPressed | QtWidgets.QAbstractItemView.DoubleClicked | QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tree_index.setObjectName("tree_index")
        item_0 = QtWidgets.QTreeWidgetItem(self.tree_index)
        item_0.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(
            QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
        self.tree_index.header().setVisible(False)
        self.push_editIndex = QtWidgets.QPushButton(self.group_index)
        self.push_editIndex.setGeometry(QtCore.QRect(40, 300, 75, 23))
        self.push_editIndex.setObjectName("push_editIndex")
        self.push_resumeIndex = QtWidgets.QPushButton(self.group_index)
        self.push_resumeIndex.setGeometry(QtCore.QRect(190, 300, 75, 23))
        self.push_resumeIndex.setObjectName("push_resumeIndex")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1073, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setTitle("")
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于深度学习的效能评估软件"))
        self.MainTitle.setText(_translate("MainWindow", "基于深度学习的效能评估软件"))
        self.label_indexLevel.setText(_translate("MainWindow", "指标层级"))
        self.label_indexName.setText(_translate("MainWindow", "指标名称"))
        self.groupBox_nodeNum.setTitle(_translate("MainWindow", "节点数量"))
        self.checkBox_lv1.setText(_translate("MainWindow", "第一层"))
        self.checkBox_lv2.setText(_translate("MainWindow", "第二层"))
        self.checkBox_lv3.setText(_translate("MainWindow", "第三层"))
        self.pushButton_selectTrain.setText(_translate("MainWindow", "选择样本数据"))
        self.command_startTrain.setText(_translate("MainWindow", "开始训练"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_train), _translate("MainWindow", "训练"))
        self.pushButton_selectEvaluate.setText(_translate("MainWindow", "选择评估数据"))
        self.command_startEvaluate.setText(_translate("MainWindow", "开始评估"))
        self.label_testIndexName.setText(_translate("MainWindow", "指标名称"))
        self.label_indexweight.setText(_translate("MainWindow", "指标权重"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_test), _translate("MainWindow", "测试"))
        self.group_evaluate.setTitle(_translate("MainWindow", "评估报告"))
        self.push_showresult.setText(_translate("MainWindow", "查看"))
        self.push_printresult.setText(_translate("MainWindow", "打印"))
        self.label_testIndexName_2.setText(_translate("MainWindow", "指标名称"))
        self.label_indexweight_2.setText(_translate("MainWindow", "评估结果"))
        self.push_retest.setText(_translate("MainWindow", "重新训练"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_evaluate), _translate("MainWindow", "评估"))
        self.group_index.setTitle(_translate("MainWindow", "指标"))
        self.tree_index.headerItem().setText(0, _translate("MainWindow", "指标体系"))
        __sortingEnabled = self.tree_index.isSortingEnabled()
        self.tree_index.setSortingEnabled(False)
        self.tree_index.topLevelItem(0).setText(0, _translate("MainWindow", "/"))
        self.tree_index.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "//"))
        self.tree_index.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(0).child(1).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(0).child(2).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(0).child(3).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(0).child(4).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(0).child(5).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(0).child(6).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(0).child(7).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "//"))
        self.tree_index.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(1).child(1).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(1).child(2).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(1).child(3).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(1).child(4).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(1).child(5).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(1).child(6).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(1).child(7).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "//"))
        self.tree_index.topLevelItem(0).child(2).child(0).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(2).child(1).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(2).child(2).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(2).child(3).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(2).child(4).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(2).child(5).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(2).child(6).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(2).child(7).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "//"))
        self.tree_index.topLevelItem(0).child(3).child(0).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(3).child(1).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(3).child(2).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(3).child(3).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(3).child(4).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(3).child(5).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(3).child(6).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(3).child(7).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "//"))
        self.tree_index.topLevelItem(0).child(4).child(0).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(4).child(1).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(4).child(2).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(4).child(3).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(4).child(4).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(4).child(5).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(4).child(6).setText(0, _translate("MainWindow", "///"))
        self.tree_index.topLevelItem(0).child(4).child(7).setText(0, _translate("MainWindow", "///"))
        self.tree_index.setSortingEnabled(__sortingEnabled)
        self.push_editIndex.setText(_translate("MainWindow", "保存"))
        self.push_resumeIndex.setText(_translate("MainWindow", "重置"))
